#!/bin/bash
set -e

echo "================================================"
echo "AI Contract Reviewer - Setup Script"
echo "================================================"
echo ""

# Check prerequisites
echo "Checking prerequisites..."
command -v node >/dev/null 2>&1 || { echo "❌ Error: Node.js is required. Install from https://nodejs.org/"; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "❌ Error: npm is required. Install from https://nodejs.org/"; exit 1; }
command -v aws >/dev/null 2>&1 || { echo "❌ Error: AWS CLI is required. Install from https://aws.amazon.com/cli/"; exit 1; }

echo "✅ All prerequisites met"
echo ""

# Configure environment variables
if [ ! -f .env ]; then
    echo "📝 Configuration Setup"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Let's configure your environment variables."
    echo "You can get your Glean credentials from:"
    echo "https://app.glean.com/admin/platform/tokenManagement"
    echo ""
    
    # Prompt for each value
    read -p "Enter your GLEAN_API_TOKEN: " GLEAN_API_TOKEN
    read -p "Enter your GLEAN_INSTANCE (e.g., your-company): " GLEAN_INSTANCE
    read -p "Enter your GLEAN_AGENT_ID: " GLEAN_AGENT_ID
    read -p "Enter your AWS_PROFILE: " AWS_PROFILE
    read -p "Enter your AWS_REGION [us-east-1]: " AWS_REGION
    AWS_REGION=${AWS_REGION:-us-east-1}
    read -p "Enter your CUSTOM_DOMAIN (e.g., addin.yourcompany.com): " CUSTOM_DOMAIN
    read -p "Enter your STANDARD_MSA_LINK (optional, press Enter to skip): " STANDARD_MSA_LINK
    
    # Create .env file with user input
    cat > .env <<EOF
# AI Contract Reviewer - Environment Variables
# Generated by setup.sh on $(date)

# Glean Configuration
GLEAN_API_TOKEN=$GLEAN_API_TOKEN
GLEAN_INSTANCE=$GLEAN_INSTANCE
GLEAN_AGENT_ID=$GLEAN_AGENT_ID

# AWS Configuration
AWS_PROFILE=$AWS_PROFILE
AWS_REGION=$AWS_REGION

# Domain Configuration
CUSTOM_DOMAIN=$CUSTOM_DOMAIN

# Optional: Link to your standard MSA document
STANDARD_MSA_LINK=$STANDARD_MSA_LINK
EOF
    
    echo ""
    echo "✅ .env file created with your configuration"
    echo ""
fi

# Load environment variables
if [ -f .env ]; then
    set -a
    source .env
    set +a
else
    echo "❌ Error: .env file not found"
    exit 1
fi

# Validate configuration
echo "Validating configuration..."
MISSING_VARS=""
[ -z "$GLEAN_API_TOKEN" ] && MISSING_VARS="$MISSING_VARS GLEAN_API_TOKEN"
[ -z "$GLEAN_INSTANCE" ] && MISSING_VARS="$MISSING_VARS GLEAN_INSTANCE"
[ -z "$GLEAN_AGENT_ID" ] && MISSING_VARS="$MISSING_VARS GLEAN_AGENT_ID"

if [ -n "$MISSING_VARS" ]; then
    echo "❌ Error: Missing required environment variables:$MISSING_VARS"
    echo "Please edit .env and set these values"
    exit 1
fi

echo "✅ Configuration valid"
echo ""

# Install dependencies
echo "Installing dependencies..."
npm install
echo "✅ Root dependencies installed"
echo ""

echo "Installing Word Add-in dependencies..."
cd word-addin && npm install && cd ..
echo "✅ Word Add-in dependencies installed"
echo ""

# Deployment choice
echo "================================================"
echo "Choose deployment option:"
echo "================================================"
echo ""
echo "1) Deploy to AWS"
echo "   - Full production setup"
echo "   - Works with Word Desktop and Online"
echo "   - Requires AWS credentials"
echo "   - Uses custom domain"
echo ""
echo "2) Skip deployment (just install dependencies)"
echo ""
read -p "Enter choice (1 or 2): " choice
echo ""

case $choice in
    1)
        # Validate AWS configuration
        if [ -z "$AWS_PROFILE" ]; then
            echo "❌ Error: AWS_PROFILE not set in .env"
            echo "Please set AWS_PROFILE and run ./setup.sh again"
            exit 1
        fi
        
        if [ -z "$CUSTOM_DOMAIN" ]; then
            echo "❌ Error: CUSTOM_DOMAIN not set in .env"
            echo "Please set CUSTOM_DOMAIN and run ./setup.sh again"
            exit 1
        fi
        
        echo "Deploying to AWS..."
        echo "This will:"
        echo "- Create S3 bucket and CloudFront distribution"
        echo "- Upload add-in files"
        echo "- Configure WAF security"
        echo ""
        cd cloudformation
        ./deploy.sh
        ;;
    2)
        echo "✅ Setup complete!"
        echo ""
        echo "Dependencies installed. You can now:"
        echo "- Run './setup.sh' again to deploy to AWS"
        echo "- Test the Glean API with: npm run test-api"
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac
